name: hipet
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
#  flutter_facebook_auth: ^3.3.3+1

  flutter_svg: ^0.21.0+1
  fluttericon: ^2.0.0

  shared_preferences: ^2.0.5
  file_picker: ^3.0.1
  dio: ^4.0.0
  get: ^4.1.4
  video_player: ^2.1.1
  bot_toast: ^4.0.1
  google_sign_in: ^5.0.4
  fluttertoast: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/animal/
    - assets/icon/logo/
    - assets/icon/svg/
    - assets/icon/

  fonts:
    - family: NotoSansKR
      fonts:
       - asset: assets/fonts/NotoSansKR-Regular.otf
       - asset: assets/fonts/NotoSansKR-Bold.otf
         weight: 600

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/logo/logo.png"