name: hipet
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_editor: ^1.1.0
  tapioca: ^1.0.2+1
  firebase_auth: ^1.1.4
  firebase_messaging: ^9.1.4
  firebase_core: ^1.1.1
  toast: ^0.1.5
  flutter_svg: ^0.21.0+1
  fluttericon: ^2.0.0
  permission_handler: ^6.1.3
  shared_preferences: ^2.0.5
  file_picker: ^3.0.1
  camera: ^0.8.1
  dio: ^4.0.0
  get: ^4.1.4
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  video_player: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/animal/
    - assets/icon/logo/
    - assets/icon/svg/
    - assets/icon/

  fonts:
    - family: NotoSansKR
      fonts:
       - asset: assets/fonts/NotoSansKR-Regular.otf
       - asset: assets/fonts/NotoSansKR-Bold.otf
         weight: 600

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/logo/logo.png"